// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTXeyiQaZ0db6ORbfaVp1w2uUiSdE2M2E',
    appId: '1:741509796231:web:b757c2adcb06bd9ca4c322',
    messagingSenderId: '741509796231',
    projectId: 'letto-78250',
    authDomain: 'letto-78250.firebaseapp.com',
    storageBucket: 'letto-78250.firebasestorage.app',
    measurementId: 'G-J98L1REMJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk6CrJtXoAh-il0RcMvVhaNaD_hn-RIEg',
    appId: '1:741509796231:android:86e9535fb1dcf1a3a4c322',
    messagingSenderId: '741509796231',
    projectId: 'letto-78250',
    storageBucket: 'letto-78250.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdW8NTSnrLI1LXvRL3mO5ZN2BOmH3EJOY',
    appId: '1:741509796231:ios:b1753b7e25cf0319a4c322',
    messagingSenderId: '741509796231',
    projectId: 'letto-78250',
    storageBucket: 'letto-78250.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

}